language: scala


script: sbt ++$TRAVIS_SCALA_VERSION test

matrix:
  include:
    - scala: 2.12.3
      env: TRAVIS_SBT_VERSION="0.13.16"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_script:
  - sudo chmod +x /usr/local/bin/sbt

